name: "Fasc√≠culo 1 / Layout A6"
on:
  push:
    branches: [salterio-liturgico]
defaults:
  run:
    working-directory: .
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Construir PDFs
        uses: ./.github/actions/lualatex
        with:
          basename: 'fasciculo1'
          layout: 'a6'
        env:
          OUT_DIR: public

      - name: Fazer upload dos artefatos
        uses: actions/upload-artifact@v3
        with:
          name: fasciculo1-a6
          path: public/
